name: fetchbook
description: A Flutter plugin for easy Facebook video downloading.
version: 1.0.0
developers:
  - name: Laxman Magarati
  - email: Laxmanmagrati@gmail.com
homepage: https://github.com/swiftsyncnp/fetchbook
repository: https://github.com/swiftsyncnp/fetchbook.git
issue_tracker: https://github.com/swiftsyncnp/fetchbook/issues

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #         weight: 700